package org.firstinspires.ftc.teamcode.TeleOpCode;

public class TeleOpVariables {
        //Declares Variables to prevent NAN
        public boolean gamepadAState;
        public boolean gamepadBState;
        public boolean gamepadDpadLeftState;
        public boolean gamepadDpadRightState;
        public boolean gamepadRightBumperState;
        public boolean gamepadYState;
        public boolean gamepadXState;
        public boolean gamepadLeftBumperState;
        public boolean gamepadBackState;
        public double gamepadLeftTrigger;
        public boolean gamepadDpadUpState;
        public boolean gamepadDpadDownState;
        public double currentRunTime;
        public double wobbleEndSet;
        public double wobbleCurrent;
        public double SOTCurrentEncoder;
        public double x;
        public double y;
        public double z;
        public double shooterSetpoint;
        public double intakePower;
        public double stagerPower;
        public double ring1Sensor;
        public double ring2Sensor;
        public double ring3Sensor;
        public double stopper = .3;
        public double xSpeedSetPoint = 1;
        public double highestMotorPower;
        public double LFM;
        public double speed;
        public double LBM;
        public double RFM;
        public double RBM;
        public boolean stagerControl = false;
        public boolean shooterControl = false;
        public double leftG1StickPoint;
        public double shooterActualVelocity;
        public double shooterPorportional;
        public double shooterPM;
        public double shooterCorrection;
        public double shooterError;
        public double timepassed;
        public double wobbleSet;
        public double wobbleError;
        public double wobblePower;
        public double wobbleP = 1.1;
        public double GRIP_S = .6;
        public double shooterLastEncoder;
        public double SOTCurrent;
        public double SOTSet = 1.47;
        public double lastTime;
        public double SOTError;
        public double SOTPower;
        public double SOTP = -20;
        public double shooterFSM = 0;
        public double WB_FSM = 5;
        public boolean WBControl = false;
        //odo variables
        public double e1current;
        public double e2current;
        public double e3current;
        public double e1Previous = 0;
        public double e2Previous = 0;
        public double e3Previous = 0;
        public double deltaE1;
        public double deltaE2;
        public double deltaE3;
        public double thetaChange;
        public double thetaInRadians;
        public double yAverage;
        public double xCoordinatePosition;
        public double yCoordinatePosition;
        public final double e2XOffSet = 1983.9474445737487;
        public final double encoderWheelDistance = 14.300650233564467;
        public double e2WithOffSet;
        public final double COUNTS_PER_INCH = 239;
        public final double encoderWheelDistanceInch = encoderWheelDistance * COUNTS_PER_INCH;

}
